// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.
// DO NOT EDIT.
export const HOST_LIFECYCLE_EVIDENCE_EVENTS = [
  "bridge_connected",
  "resource_delivered",
  "app_initialized",
  "app_error",
] as const;

export type HostLifecycleEvidenceEvent =
  (typeof HOST_LIFECYCLE_EVIDENCE_EVENTS)[number];

export const DEFAULT_AWAIT_EVIDENCE_EVENT =
  "app_initialized" as const;
