#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../..");
const canonicalPath = path.join(repoRoot, "contracts", "lifecycle-contract.json");

const checkMode = process.argv.includes("--check");

const canonical = JSON.parse(await readFile(canonicalPath, "utf8"));
validateCanonical(canonical);

const outputs = new Map([
  [
    path.join(repoRoot, "services", "roomd", "src", "lifecycle-contract.generated.ts"),
    renderRoomdTs(canonical),
  ],
  [
    path.join(repoRoot, "apps", "host-web", "src", "room-canvas", "lifecycle-contract.generated.ts"),
    renderHostTs(canonical),
  ],
  [
    path.join(repoRoot, "tools", "roomctl", "internal", "roomctl", "cli", "lifecycle_contract_generated.go"),
    renderRoomctlGo(canonical),
  ],
]);

const mismatches = [];
for (const [filePath, expected] of outputs.entries()) {
  if (checkMode) {
    const actual = await readFile(filePath, "utf8").catch(() => "");
    if (actual !== expected) {
      mismatches.push(path.relative(repoRoot, filePath));
    }
    continue;
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, expected, "utf8");
  // eslint-disable-next-line no-console
  console.log(`updated ${path.relative(repoRoot, filePath)}`);
}

if (checkMode) {
  if (mismatches.length > 0) {
    // eslint-disable-next-line no-console
    console.error("lifecycle contract drift detected in:");
    for (const filePath of mismatches) {
      // eslint-disable-next-line no-console
      console.error(`- ${filePath}`);
    }
    process.exit(1);
  }
  // eslint-disable-next-line no-console
  console.log("lifecycle contract generated files are in sync");
}

function validateCanonical(value) {
  const events = value?.hostLifecycleEvidenceEvents;
  const defaultEvent = value?.defaultAwaitEvidenceEvent;

  if (!Array.isArray(events) || events.length === 0 || !events.every((entry) => typeof entry === "string" && entry.trim() !== "")) {
    throw new Error("contracts/lifecycle-contract.json: hostLifecycleEvidenceEvents must be a non-empty string array");
  }
  if (typeof defaultEvent !== "string" || defaultEvent.trim() === "") {
    throw new Error("contracts/lifecycle-contract.json: defaultAwaitEvidenceEvent must be a non-empty string");
  }
  if (!events.includes(defaultEvent)) {
    throw new Error("contracts/lifecycle-contract.json: defaultAwaitEvidenceEvent must exist in hostLifecycleEvidenceEvents");
  }
}

function renderTsHeader() {
  return [
    "// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.",
    "// DO NOT EDIT.",
    "",
  ].join("\n");
}

function renderGoHeader() {
  return [
    "// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.",
    "// DO NOT EDIT.",
    "",
  ].join("\n");
}

function renderHostTs(canonicalContract) {
  const eventsLiteral = canonicalContract.hostLifecycleEvidenceEvents
    .map((event) => `  \"${event}\",`)
    .join("\n");

  return `${renderTsHeader()}export const HOST_LIFECYCLE_EVIDENCE_EVENTS = [\n${eventsLiteral}\n] as const;\n\nexport type HostLifecycleEvidenceEvent =\n  (typeof HOST_LIFECYCLE_EVIDENCE_EVENTS)[number];\n\nexport const DEFAULT_AWAIT_EVIDENCE_EVENT =\n  \"${canonicalContract.defaultAwaitEvidenceEvent}\" as const;\n`;
}

function renderRoomdTs(canonicalContract) {
  return renderHostTs(canonicalContract);
}

function renderRoomctlGo(canonicalContract) {
  const eventsLiteral = canonicalContract.hostLifecycleEvidenceEvents
    .map((event) => `\t\"${event}\",`)
    .join("\n");

  return `${renderGoHeader()}package cli\n\nvar HostLifecycleEvidenceEvents = []string{\n${eventsLiteral}\n}\n\nconst DefaultAwaitEvidenceEvent = \"${canonicalContract.defaultAwaitEvidenceEvent}\"\n`;
}
