#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../..");
const canonicalPath = path.join(repoRoot, "contracts", "lifecycle-contract.json");

const checkMode = process.argv.includes("--check");

const canonical = JSON.parse(await readFile(canonicalPath, "utf8"));
validateCanonical(canonical);

const outputs = new Map([
  [
    path.join(repoRoot, "services", "roomd", "src", "lifecycle-contract.generated.ts"),
    renderRoomdTs(canonical),
  ],
  [
    path.join(repoRoot, "apps", "host-web", "src", "room-canvas", "lifecycle-contract.generated.ts"),
    renderHostTs(canonical),
  ],
  [
    path.join(repoRoot, "tools", "roomctl", "internal", "roomctl", "cli", "lifecycle_contract_generated.go"),
    renderRoomctlGo(canonical),
  ],
]);

const mismatches = [];
for (const [filePath, expected] of outputs.entries()) {
  if (checkMode) {
    const actual = await readFile(filePath, "utf8").catch(() => "");
    if (actual !== expected) {
      mismatches.push(path.relative(repoRoot, filePath));
    }
    continue;
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, expected, "utf8");
  // eslint-disable-next-line no-console
  console.log(`updated ${path.relative(repoRoot, filePath)}`);
}

if (checkMode) {
  if (mismatches.length > 0) {
    // eslint-disable-next-line no-console
    console.error("lifecycle contract drift detected in:");
    for (const filePath of mismatches) {
      // eslint-disable-next-line no-console
      console.error(`- ${filePath}`);
    }
    process.exit(1);
  }
  // eslint-disable-next-line no-console
  console.log("lifecycle contract generated files are in sync");
}

function validateCanonical(value) {
  const events = value?.hostLifecycleEvidenceEvents;
  const defaultEvent = value?.defaultAwaitEvidenceEvent;
  const ontology = value?.ontology;
  const canonicalNoun = ontology?.canonicalNoun;
  const compatibilityNoun = ontology?.legacyCompatibilityNoun;
  const canonicalIngressRoute = ontology?.canonicalIngressRoute;
  const compatibilityIngressRoute = ontology?.compatibilityIngressRoute;
  const compatibilityStatus = ontology?.compatibilityStatus;
  const compatibilityRemovalIssue = ontology?.compatibilityRemovalIssue;
  const compatibilitySunsetNotBefore = ontology?.compatibilitySunsetNotBefore;

  if (!Array.isArray(events) || events.length === 0 || !events.every((entry) => typeof entry === "string" && entry.trim() !== "")) {
    throw new Error("contracts/lifecycle-contract.json: hostLifecycleEvidenceEvents must be a non-empty string array");
  }
  if (typeof defaultEvent !== "string" || defaultEvent.trim() === "") {
    throw new Error("contracts/lifecycle-contract.json: defaultAwaitEvidenceEvent must be a non-empty string");
  }
  if (!events.includes(defaultEvent)) {
    throw new Error("contracts/lifecycle-contract.json: defaultAwaitEvidenceEvent must exist in hostLifecycleEvidenceEvents");
  }
  if (
    typeof canonicalNoun !== "string" ||
    canonicalNoun.trim() === ""
  ) {
    throw new Error("contracts/lifecycle-contract.json: ontology.canonicalNoun must be a non-empty string");
  }
  if (
    typeof compatibilityNoun !== "string" ||
    compatibilityNoun.trim() === ""
  ) {
    throw new Error("contracts/lifecycle-contract.json: ontology.legacyCompatibilityNoun must be a non-empty string");
  }
  if (
    typeof canonicalIngressRoute !== "string" ||
    !canonicalIngressRoute.includes("/:roomId/instances/:instanceId/")
  ) {
    throw new Error(
      "contracts/lifecycle-contract.json: ontology.canonicalIngressRoute must include /:roomId/instances/:instanceId/",
    );
  }
  if (
    typeof compatibilityIngressRoute !== "string" ||
    !compatibilityIngressRoute.includes("/:roomId/instances/:instanceId/")
  ) {
    throw new Error(
      "contracts/lifecycle-contract.json: ontology.compatibilityIngressRoute must include /:roomId/instances/:instanceId/",
    );
  }
  if (typeof compatibilityStatus !== "string" || compatibilityStatus.trim() === "") {
    throw new Error("contracts/lifecycle-contract.json: ontology.compatibilityStatus must be a non-empty string");
  }
  if (!Number.isInteger(compatibilityRemovalIssue) || compatibilityRemovalIssue <= 0) {
    throw new Error("contracts/lifecycle-contract.json: ontology.compatibilityRemovalIssue must be a positive integer");
  }
  if (
    typeof compatibilitySunsetNotBefore !== "string" ||
    !/^\d{4}-\d{2}-\d{2}$/.test(compatibilitySunsetNotBefore)
  ) {
    throw new Error(
      "contracts/lifecycle-contract.json: ontology.compatibilitySunsetNotBefore must be a YYYY-MM-DD date string",
    );
  }
}

function renderTsHeader() {
  return [
    "// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.",
    "// DO NOT EDIT.",
    "",
  ].join("\n");
}

function renderGoHeader() {
  return [
    "// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.",
    "// DO NOT EDIT.",
    "",
  ].join("\n");
}

function renderHostTs(canonicalContract) {
  const eventsLiteral = canonicalContract.hostLifecycleEvidenceEvents
    .map((event) => `  \"${event}\",`)
    .join("\n");

  const ontology = canonicalContract.ontology;

  return `${renderTsHeader()}export const HOST_LIFECYCLE_EVIDENCE_EVENTS = [\n${eventsLiteral}\n] as const;\n\nexport type HostLifecycleEvidenceEvent =\n  (typeof HOST_LIFECYCLE_EVIDENCE_EVENTS)[number];\n\nexport const DEFAULT_AWAIT_EVIDENCE_EVENT =\n  \"${canonicalContract.defaultAwaitEvidenceEvent}\" as const;\n\nexport const LIFECYCLE_CANONICAL_NOUN =\n  \"${ontology.canonicalNoun}\" as const;\n\nexport const LIFECYCLE_COMPATIBILITY_NOUN =\n  \"${ontology.legacyCompatibilityNoun}\" as const;\n\nexport const LIFECYCLE_CANONICAL_INGRESS_ROUTE =\n  \"${ontology.canonicalIngressRoute}\" as const;\n\nexport const LIFECYCLE_COMPATIBILITY_INGRESS_ROUTE =\n  \"${ontology.compatibilityIngressRoute}\" as const;\n\nexport const LIFECYCLE_COMPATIBILITY_STATUS =\n  \"${ontology.compatibilityStatus}\" as const;\n\nexport const LIFECYCLE_COMPATIBILITY_REMOVAL_ISSUE =\n  ${ontology.compatibilityRemovalIssue} as const;\n\nexport const LIFECYCLE_COMPATIBILITY_SUNSET_NOT_BEFORE =\n  \"${ontology.compatibilitySunsetNotBefore}\" as const;\n`;
}

function renderRoomdTs(canonicalContract) {
  return renderHostTs(canonicalContract);
}

function renderRoomctlGo(canonicalContract) {
  const eventsLiteral = canonicalContract.hostLifecycleEvidenceEvents
    .map((event) => `\t\"${event}\",`)
    .join("\n");

  const ontology = canonicalContract.ontology;

  return `${renderGoHeader()}package cli\n\nvar HostLifecycleEvidenceEvents = []string{\n${eventsLiteral}\n}\n\nconst DefaultAwaitEvidenceEvent = \"${canonicalContract.defaultAwaitEvidenceEvent}\"\nconst LifecycleCanonicalNoun = \"${ontology.canonicalNoun}\"\nconst LifecycleCompatibilityNoun = \"${ontology.legacyCompatibilityNoun}\"\nconst LifecycleCanonicalIngressRoute = \"${ontology.canonicalIngressRoute}\"\nconst LifecycleCompatibilityIngressRoute = \"${ontology.compatibilityIngressRoute}\"\nconst LifecycleCompatibilityStatus = \"${ontology.compatibilityStatus}\"\nconst LifecycleCompatibilityRemovalIssue = ${ontology.compatibilityRemovalIssue}\nconst LifecycleCompatibilitySunsetNotBefore = \"${ontology.compatibilitySunsetNotBefore}\"\n`;
}
