// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.
// DO NOT EDIT.
export const HOST_LIFECYCLE_EVIDENCE_EVENTS = [
  "bridge_connected",
  "resource_delivered",
  "app_initialized",
  "app_error",
] as const;

export type HostLifecycleEvidenceEvent =
  (typeof HOST_LIFECYCLE_EVIDENCE_EVENTS)[number];

export const DEFAULT_AWAIT_EVIDENCE_EVENT =
  "app_initialized" as const;

export const LIFECYCLE_CANONICAL_NOUN =
  "lifecycle" as const;

export const LIFECYCLE_COMPATIBILITY_NOUN =
  "evidence" as const;

export const LIFECYCLE_CANONICAL_INGRESS_ROUTE =
  "/rooms/:roomId/instances/:instanceId/lifecycle" as const;

export const LIFECYCLE_COMPATIBILITY_INGRESS_ROUTE =
  "/rooms/:roomId/instances/:instanceId/evidence" as const;

export const LIFECYCLE_COMPATIBILITY_STATUS =
  "removed" as const;

export const LIFECYCLE_COMPATIBILITY_REMOVAL_ISSUE =
  43 as const;

export const LIFECYCLE_COMPATIBILITY_SUNSET_NOT_BEFORE =
  "2026-04-07" as const;
