// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.
// DO NOT EDIT.
package cli

var HostLifecycleEvidenceEvents = []string{
	"bridge_connected",
	"resource_delivered",
	"app_initialized",
	"app_error",
}

const DefaultAwaitEvidenceEvent = "app_initialized"
