// Code generated by tools/lifecycle-contract/sync.mjs from contracts/lifecycle-contract.json.
// DO NOT EDIT.
package cli

var HostLifecycleEvidenceEvents = []string{
	"bridge_connected",
	"resource_delivered",
	"app_initialized",
	"app_error",
}

const DefaultAwaitEvidenceEvent = "app_initialized"
const LifecycleCanonicalNoun = "lifecycle"
const LifecycleCompatibilityNoun = "evidence"
const LifecycleCanonicalIngressRoute = "/rooms/:roomId/instances/:instanceId/lifecycle"
const LifecycleCompatibilityIngressRoute = "/rooms/:roomId/instances/:instanceId/evidence"
const LifecycleCompatibilityStatus = "deprecated"
const LifecycleCompatibilityRemovalIssue = 43
const LifecycleCompatibilitySunsetNotBefore = "2026-12-31"
